export const states = [
    { value: 'AGS', name: 'AGUASCALIENTES' },
    { value: 'BC', name: 'BAJA CALIFORNIA' },
    { value: 'BCS', name: 'BAJA CALIFORNIA SUR' },
    { value: 'CHI', name: 'CHIHUAHUA' },
    { value: 'CHS', name: 'CHIAPAS' },
    { value: 'CMP', name: 'CAMPECHE' },
    { value: 'CMX', name: 'CIUDAD DE MEXICO' },
    { value: 'COA', name: 'COAHUILA' },
    { value: 'COL', name: 'COLIMA' },
    { value: 'DGO', name: 'DURANGO' },
    { value: 'GRO', name: 'GUERRERO' },
    { value: 'GTO', name: 'GUANAJUATO' },
    { value: 'HGO', name: 'HIDALGO' },
    { value: 'JAL', name: 'JALISCO' },
    { value: 'MCH', name: 'MICHOACAN' },
    { value: 'MEX', name: 'ESTADO DE MEXICO' },
    { value: 'MOR', name: 'MORELOS' },
    { value: 'NAY', name: 'NAYARIT' },
    { value: 'NL', name: 'NUEVO LEON' },
    { value: 'OAX', name: 'OAXACA' },
    { value: 'PUE', name: 'PUEBLA' },
    { value: 'QR', name: 'QUINTANA ROO' },
    { value: 'QRO', name: 'QUERETARO' },
    { value: 'SIN', name: 'SINALOA' },
    { value: 'SLP', name: 'SAN LUIS POTOSI' },
    { value: 'SON', name: 'SONORA' },
    { value: 'TAB', name: 'TABASCO' },
    { value: 'TLX', name: 'TLAXCALA' },
    { value: 'TMS', name: 'TAMAULIPAS' },
    { value: 'VER', name: 'VERACRUZ' },
    { value: 'YUC', name: 'YUCATAN' },
    { value: 'ZAC', name: 'ZACATECAS' },
];
